project_id = "kagwfntxlgzrcngysmlt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.secure-admin-operations]
verify_jwt = true

[functions.enhanced-auth-security]
verify_jwt = false

[functions.security-monitor]
verify_jwt = true

[functions.security-metrics]
verify_jwt = true