-- Populate course_modules with existing course data
INSERT INTO public.course_modules (module_id, title, description, skill_level, duration, lessons_count, order_index, prerequisites, is_active) VALUES
('foundations', 'Halo Business Finance Foundations', 'Master the core business finance principles used at Halo Business Finance. This comprehensive module covers financial statement analysis, risk assessment, and decision-making frameworks essential for success in commercial lending and business finance.', 'beginner', '2.5 hours', 12, 0, '{}', true),
('capital-markets', 'Halo Capital Markets & Lending Systems', 'Explore capital markets through Halo Business Finance''s perspective. Learn how institutional funding, secondary markets, and capital allocation impact commercial lending decisions and portfolio management strategies.', 'intermediate', '3 hours', 15, 1, '{"foundations"}', true),
('risk-management', 'Advanced Risk Management & Analysis', 'Deep dive into sophisticated risk assessment methodologies used in commercial lending. Learn to identify, measure, and mitigate various types of lending risks while maintaining profitable loan portfolios.', 'intermediate', '2.5 hours', 14, 2, '{"foundations"}', true),
('regulatory-compliance', 'Banking Regulations & Compliance', 'Navigate the complex regulatory environment of commercial lending. Understand key regulations, compliance requirements, and how regulatory changes impact lending decisions and portfolio management.', 'expert', '3.5 hours', 16, 3, '{"foundations", "capital-markets"}', true),
('commercial-underwriting', 'Commercial Loan Underwriting Mastery', 'Master the art and science of commercial loan underwriting. Learn advanced analysis techniques, deal structuring, and decision-making frameworks used by top commercial lenders.', 'expert', '4 hours', 18, 4, '{"foundations", "risk-management"}', true),
('portfolio-management', 'Portfolio Management & Performance Optimization', 'Learn portfolio-level strategies for managing commercial loan portfolios. Understand diversification, risk-adjusted returns, and performance optimization techniques.', 'expert', '3 hours', 13, 5, '{"commercial-underwriting", "risk-management"}', true),
('digital-transformation', 'Digital Banking & Fintech Integration', 'Explore how digital transformation is reshaping commercial lending. Learn about fintech partnerships, automation, and technology-driven lending solutions.', 'intermediate', '2 hours', 10, 6, '{"foundations"}', true),
('leadership-development', 'Leadership in Commercial Banking', 'Develop leadership skills specific to commercial banking environments. Learn to manage teams, drive performance, and lead change initiatives in banking organizations.', 'expert', '3.5 hours', 15, 7, '{"commercial-underwriting", "portfolio-management"}', true);

-- Populate course_videos with foundation module videos
INSERT INTO public.course_videos (module_id, title, description, video_type, video_url, youtube_id, thumbnail_url, order_index, is_active, tags) VALUES
('foundations', 'Welcome to Halo Business Finance Training', 'Introduction to Halo''s approach to business finance and commercial lending excellence', 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 0, true, '{"introduction", "overview", "halo"}'),
('foundations', 'Halo''s Financial Statement Analysis Framework', 'Learn Halo''s proprietary methods for analyzing business financial health and creditworthiness', 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 1, true, '{"financial-analysis", "framework", "creditworthiness"}'),
('foundations', 'Time Value of Money & NPV Calculations', 'Master present value, future value, and net present value concepts', 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 2, true, '{"time-value", "npv", "calculations"}'),
('foundations', 'Working Capital Management Strategies', 'Learn to optimize cash, inventory, and receivables management', 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 3, true, '{"working-capital", "cash-management", "receivables"}'),
('capital-markets', 'Capital Markets Overview & Structure', 'Introduction to primary and secondary markets and their functions', 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 0, true, '{"capital-markets", "structure", "overview"}'),
('capital-markets', 'Equity Markets & Stock Valuation', 'Understanding stock markets, IPOs, and equity valuation methods', 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 1, true, '{"equity", "valuation", "ipo"}');